# Generated by Django 5.0.9 on 2025-11-23 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Denormalized for performance",
                        max_length=255,
                        verbose_name="customer name",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                (
                    "duration_minutes",
                    models.IntegerField(verbose_name="duration (minutes)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "appointment",
                "verbose_name_plural": "appointments",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Blocker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                (
                    "duration_minutes",
                    models.IntegerField(verbose_name="duration (minutes)"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
            ],
            options={
                "verbose_name": "blocker",
                "verbose_name_plural": "blockers",
                "ordering": ["start_time"],
            },
        ),
    ]
