# Generated by Django 5.0.9 on 2025-11-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("core", "0001_initial"),
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="business",
            field=models.ForeignKey(
                help_text="Business this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"role": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned resource (null if unassigned)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="resources.resource",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="resources.service",
            ),
        ),
        migrations.AddField(
            model_name="blocker",
            name="business",
            field=models.ForeignKey(
                help_text="Business this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="blocker",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blockers",
                to="resources.resource",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["business", "start_time"], name="bookings_ap_busines_980d80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["business", "resource", "start_time"],
                name="bookings_ap_busines_5459e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["business", "customer"], name="bookings_ap_busines_3c8356_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blocker",
            index=models.Index(
                fields=["business", "resource", "start_time"],
                name="bookings_bl_busines_fad3ab_idx",
            ),
        ),
    ]
