# Generated by Django 5.0.9 on 2025-11-23 08:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="business name"),
                ),
                (
                    "subdomain",
                    models.SlugField(
                        help_text="URL subdomain (e.g., 'acme' for acme.smoothschedule.com)",
                        max_length=100,
                        unique=True,
                        verbose_name="subdomain",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="primary color"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#10B981", max_length=7, verbose_name="secondary color"
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="logo URL"),
                ),
                (
                    "whitelabel_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Hide platform branding",
                        verbose_name="white-label enabled",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("Free", "Free"),
                            ("Professional", "Professional"),
                            ("Business", "Business"),
                            ("Enterprise", "Enterprise"),
                        ],
                        default="Free",
                        max_length=20,
                        verbose_name="subscription plan",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("Trial", "Trial"),
                        ],
                        default="Active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                (
                    "resources_can_reschedule",
                    models.BooleanField(
                        default=False,
                        help_text="Allow staff to reschedule their own appointments",
                        verbose_name="resources can reschedule",
                    ),
                ),
                (
                    "require_payment_method_to_book",
                    models.BooleanField(
                        default=False, verbose_name="require payment method"
                    ),
                ),
                (
                    "cancellation_window_hours",
                    models.IntegerField(
                        default=24, verbose_name="cancellation window (hours)"
                    ),
                ),
                (
                    "late_cancellation_fee_percent",
                    models.IntegerField(
                        default=0, verbose_name="late cancellation fee %"
                    ),
                ),
                (
                    "initial_setup_complete",
                    models.BooleanField(default=False, verbose_name="setup complete"),
                ),
                (
                    "active_template_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="active template"
                    ),
                ),
                (
                    "website_content",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="website content"
                    ),
                ),
                (
                    "website_pages",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="website pages"
                    ),
                ),
            ],
            options={
                "verbose_name": "business",
                "verbose_name_plural": "businesses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superuser", "Superuser"),
                            ("platform_manager", "Platform Manager"),
                            ("platform_support", "Platform Support"),
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                            ("resource", "Resource"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="avatar URL"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "indexes": [
                    models.Index(
                        fields=["business", "email"],
                        name="core_user_busines_1b3d47_idx",
                    ),
                    models.Index(
                        fields=["business", "role"], name="core_user_busines_596ccc_idx"
                    ),
                ],
                "unique_together": {("email", "business")},
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
