# Generated by Django 5.0.9 on 2025-11-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="0=Monday, 6=Sunday",
                        verbose_name="day of week",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time business opens (e.g., 09:00:00)",
                        null=True,
                        verbose_name="opening time",
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time business closes (e.g., 17:00:00)",
                        null=True,
                        verbose_name="closing time",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Check if business is closed this day",
                        verbose_name="closed",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "business hours",
                "verbose_name_plural": "business hours",
                "ordering": ["day_of_week", "open_time"],
                "indexes": [
                    models.Index(
                        fields=["business", "day_of_week"],
                        name="core_busine_busines_2811e7_idx",
                    )
                ],
            },
        ),
    ]
